:schedule:
  update_subscriptions:
    cron: '0 0 5 */1 * *'  # Runs at 5:00:00, every 1 day
    class: SubscriptionsDataUpdateWorker
  update_all_movies_data:
    cron: '0 0 0 */7 * *'  # Runs at 00:00:00, every 7 day
    class: ParseRemoteMovieDataWorker
